# Generated by Django 4.2.2 on 2023-06-26 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ref_Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('singer', models.CharField(default=None, max_length=10)),
                ('video_file', models.FileField(default=0, upload_to='ref_video/')),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='ref_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(default=0, upload_to='challenge_upload/'),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('video_file', models.FileField(default=0, upload_to='output/')),
                ('ref_id', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
