# Generated by Django 4.2.2 on 2023-06-26 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_ref_video_remove_video_title_remove_video_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='title',
        ),
        migrations.RemoveField(
            model_name='score',
            name='user',
        ),
    ]
