# Generated by Django 4.2.2 on 2023-06-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_score_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.FloatField(),
        ),
    ]
